local vars = require("vars")

hl.on("hyprland.start", function()
	hl.exec_cmd(vars.terminal)
	hl.exec_cmd("awww-daemon && sleep 0.5 && awww restore")
	--hl.exec_cmd("nm-applet")
	hl.exec_cmd("waybar")
	hl.exec_cmd(vars.browser)
	hl.exec_cmd("vesktop")
	hl.exec_cmd("spotify-launcher")
	hl.exec_cmd("flatpak run com.stremio.Stremio")
end)
